development: &non_production_settings
  site_url: http://localhost:3000
  site_name: TechReach Development
  admin_email: bort@bort.com
  
test:
  <<: *non_production_settings

staging:
  site_url: http://staging.example.com
  site_name: TechReach
  admin_email: bort@bort.com  
  
production:
  site_url: http://www.example.com
  site_name: TechReach
  admin_email: bort@bort.com
