development: &non_production_settings
  site_url: http://localhost:3000
  site_name: TechReach Development
  admin_email: admin@bhamtechreach.org
  
test:
  <<: *non_production_settings

staging:
  site_url: http://staging.birminghamtechreach.org
  site_name: TechReach
  admin_email: admin@bhamtechreach.org  
  
production:
  site_url: http://www.birminghamtechreach.org
  site_name: TechReach
  admin_email: admin@bhamtechreach.org
